service: aws-lambda-qrda-conversion

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8 
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: us-east-1
  memorySize: 512
  timeout: 15
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
custom:
  defaultStage: dev
  profiles:
    dev: default 

package:
  artifact: lambdize/target/lambdize.jar

functions:
  convertFile:
    handler: gov.cms.qpp.conversion.aws.ConversionHandler
    events:
      - s3:
          bucket: qrda-conversion-files
          event: s3:ObjectCreated:*